apiVersion: v1
kind: ConfigMap
metadata:
  name: ffdd-config
  namespace: ffdd
data:
  NODE_ENV: "production"
  CLIENT_URL: "http://localhost:5173"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX_REQUESTS: "1000"
  JWT_EXPIRES_IN: "24h"
  JWT_REFRESH_EXPIRES_IN: "7d"
  JWT_RESET_EXPIRES_IN: "1h"
  # Service URLs (internal)
  USER_SERVICE_URL: "http://user-service:3002"
  RESTAURANT_SERVICE_URL: "http://restaurant-service:3003"
  ORDER_SERVICE_URL: "http://order-service:3004"
  DRONE_SERVICE_URL: "http://drone-service:3005"
  PAYMENT_SERVICE_URL: "http://payment-service:3006"
  # MongoDB
  MONGO_INITDB_DATABASE: "drone"
  # MoMo Payment (optional)
  MOMO_ENDPOINT_CREATE: "https://test-payment.momo.vn/v2/gateway/api/create"

