apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ffdd

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mongodb.yaml
  - api-gateway.yaml
  - user-service.yaml
  - restaurant-service.yaml
  - order-service.yaml
  - drone-service.yaml
  - payment-service.yaml
  - client.yaml

