apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ffdd2

# Reference the base kustomization at k8s/ (must contain a kustomization.yaml)
resources:
  - ../..
  - namespace-ffdd2.yaml
